include: package:lint/analysis_options.yaml

linter:
  rules:
    avoid_function_literals_in_foreach_calls: false
    overridden_fields: false
    prefer_single_quotes: true
    sort_pub_dependencies: false
