name: walue_app
description: An app for tracking the profit from cryptocurrencies.

publish_to: "none"

version: 0.1.11+21

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  beamer: 0.14.1

  easy_localization: 3.0.1

  introduction_screen: 2.1.0

  flutter_riverpod: 0.14.0+3
  hooks_riverpod: 0.14.0+3

  google_fonts: 2.3.3
  font_awesome_flutter: 9.2.0

  shared_preferences: 2.0.18

  stream_transform: 2.1.0

  firebase_core: 1.24.0
  firebase_auth: 3.11.2
  firebase_analytics: 9.3.8
  firebase_crashlytics: 2.9.0
  firebase_performance: 0.9.0+6

  cloud_functions: 3.3.9
  cloud_firestore: 3.5.1

  google_mobile_ads: 1.3.0

  google_sign_in: 5.4.4
  sign_in_with_apple: 3.3.0

  dio: 4.0.6
  dio_cache_interceptor: 3.4.0
  dio_cache_interceptor_hive_store: 3.2.1

  path_provider: 2.0.13

  quiver: 3.1.0

  pattern_formatter: 2.0.0

  lint: 1.10.0

  intl: 0.17.0

  decimal: 1.5.0

  crypto: 3.0.2

  auto_size_text: 3.0.0

  flutter_hooks: 0.18.6

  cached_network_image: 3.2.3

  url_launcher: 6.1.10

  video_player: 2.4.8

dev_dependencies:
  flutter_launcher_icons: 0.12.0

  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/guide/
    - assets/icons/
    - google_fonts/

flutter_icons:
  image_path_android: "../walue_branding/icon.png"
  image_path_ios: "../walue_branding/icon_512.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "../walue_branding/icon_background.png"
  adaptive_icon_foreground: "../walue_branding/icon_foreground.png"
