name: walue_app
description: An app for tracking the profit from cryptocurrencies.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  beamer: 1.0.0-nullsafety.3

  flutter_riverpod: 0.13.1

  google_fonts: 2.0.0

  shared_preferences: 2.0.5

  stream_transform: 2.0.0

  firebase_core: 1.0.1
  firebase_auth: 1.0.1

  cloud_firestore: 1.0.1

  google_sign_in: 5.0.1

  dio: 4.0.0-beta7

  lint: 1.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - google_fonts/
