name: walue_app
description: An app for tracking the profit from cryptocurrencies.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  beamer: 0.12.4

  flutter_riverpod: 0.14.0

  google_fonts: 2.0.0
  font_awesome_flutter: 9.0.0

  shared_preferences: 2.0.5

  stream_transform: 2.0.0

  firebase_core: 1.1.0
  firebase_auth: 1.1.3

  cloud_firestore: 2.0.0

  google_sign_in: 5.0.2

  dio: 4.0.0
  dio_cache_interceptor: 2.3.0

  path_provider: 2.0.1

  quiver: 3.0.1

  pattern_formatter: 2.0.0

  lint: 1.5.3

  intl: 0.17.0

  decimal: 1.1.0

  auto_size_text: 3.0.0-nullsafety.0

dev_dependencies:
  flutter_launcher_icons: 0.9.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - google_fonts/

flutter_icons:
  image_path: "../walue_branding/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "../walue_branding/icon_background.png"
  adaptive_icon_foreground: "../walue_branding/icon_foreground.png"
