name: walue_app
description: An app for tracking the profit from cryptocurrencies.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  beamer: 0.12.1

  flutter_riverpod: 0.14.0

  google_fonts: 2.0.0
  font_awesome_flutter: 9.0.0

  shared_preferences: 2.0.5

  stream_transform: 2.0.0

  firebase_core: 1.0.3
  firebase_auth: 1.1.1

  cloud_firestore: 1.0.6

  google_sign_in: 5.0.2

  dio: 4.0.0
  dio_cache_interceptor: 2.1.1

  sqlite3_flutter_libs: 0.4.1
  path_provider: 2.0.1

  quiver: 3.0.1

  pattern_formatter: 2.0.0

  lint: 1.5.3

  intl: 0.17.0

  decimal: 1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - google_fonts/
